
token_key: yawei is the honorest in the worlds
url_prefix: /api/v1
domain_port: http://www.datasview.com:8000
auth_test_mode: True
ip_test_mode: True
allow_link_ip:
- 35.241.66.226

mods: 
  f-mod: 
    name: f-mod
    version: 1
    has_mdl: False
    tags: 
    - 模组的名字
    



