

mod_settings: 
  name: fmod
  version: 1
  has_mdl: True
  has_sitemap: True
  route:
    route_prefix: fmod
    tags: 
    - 模组的名字


site_maps:
  single_sites:
    fmod: 
    - link: /
      lastmod: 2021-2-6
      changefreq: weekly
      priority: 1.0
  db_sites: 
    fmod:
      mdls: 
      - table: Fmod
        link_key: name
        lastmod_key: update_date
        prefix: fmod/ # 前缀
      priority: 0.9
      changefreq: daily